// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollService.Properties.Data;

#nullable disable

namespace PayrollService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806093206_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayrollService.Models.EmployeeLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeLoans");
                });

            modelBuilder.Entity("PayrollService.Models.Payslip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Allowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cpfemployee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cpfemployer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtherDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SocialSecurity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThirteenthMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<decimal>("YearEndBonus")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payslips");
                });

            modelBuilder.Entity("PayrollService.Models.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxBrackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Myanmar",
                            Description = "0% - Up to 4.8M MMK",
                            MaxIncome = 4800000m,
                            MinIncome = 0m,
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = 2,
                            Country = "Myanmar",
                            Description = "5% - 4.8M to 10M MMK",
                            MaxIncome = 10000000m,
                            MinIncome = 4800001m,
                            TaxRate = 5m
                        },
                        new
                        {
                            Id = 3,
                            Country = "Myanmar",
                            Description = "10% - 10M to 20M MMK",
                            MaxIncome = 20000000m,
                            MinIncome = 10000001m,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 4,
                            Country = "Myanmar",
                            Description = "15% - 20M to 30M MMK",
                            MaxIncome = 30000000m,
                            MinIncome = 20000001m,
                            TaxRate = 15m
                        },
                        new
                        {
                            Id = 5,
                            Country = "Myanmar",
                            Description = "20% - Above 30M MMK",
                            MaxIncome = 999999999m,
                            MinIncome = 30000001m,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 6,
                            Country = "Singapore_Employee_55below",
                            Description = "CPF Employee 20% (age 55 and below)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 7,
                            Country = "Singapore_Employer_55below",
                            Description = "CPF Employer 17% (age 55 and below)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 17m
                        },
                        new
                        {
                            Id = 8,
                            Country = "Singapore_Employee_55to60",
                            Description = "CPF Employee 15% (age 55-60)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 15m
                        },
                        new
                        {
                            Id = 9,
                            Country = "Singapore_Employer_55to60",
                            Description = "CPF Employer 13% (age 55-60)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 13m
                        },
                        new
                        {
                            Id = 10,
                            Country = "Singapore_Employee_60to65",
                            Description = "CPF Employee 9.5% (age 60-65)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 9.5m
                        },
                        new
                        {
                            Id = 11,
                            Country = "Singapore_Employer_60to65",
                            Description = "CPF Employer 9% (age 60-65)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 9m
                        },
                        new
                        {
                            Id = 12,
                            Country = "Singapore_Employee_65above",
                            Description = "CPF Employee 7% (age above 65)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 7m
                        },
                        new
                        {
                            Id = 13,
                            Country = "Singapore_Employer_65above",
                            Description = "CPF Employer 7.5% (age above 65)",
                            MaxIncome = 999999999m,
                            MinIncome = 0m,
                            TaxRate = 7.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
