// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollService.Data;

#nullable disable

namespace PayrollService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811043548_AddDepartmentName")]
    partial class AddDepartmentName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayrollService.Models.AgeBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EmployeeRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("EmployerRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AgeBrackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "SG",
                            Description = "Age 55 and below",
                            EmployeeRate = 20m,
                            EmployerRate = 17m,
                            MaxAge = 55,
                            MinAge = 0
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "SG",
                            Description = "Age 56 to 60",
                            EmployeeRate = 15m,
                            EmployerRate = 13m,
                            MaxAge = 60,
                            MinAge = 56
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "SG",
                            Description = "Age 61 to 65",
                            EmployeeRate = 9.5m,
                            EmployerRate = 9m,
                            MaxAge = 65,
                            MinAge = 61
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "SG",
                            Description = "Age above 65",
                            EmployeeRate = 7m,
                            EmployerRate = 7.5m,
                            MaxAge = 999,
                            MinAge = 66
                        });
                });

            modelBuilder.Entity("PayrollService.Models.CountryPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagEmoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAgeBased")
                        .HasColumnType("bit");

                    b.Property<bool>("HasProgressiveTax")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("SocialContributionEmployeeRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SocialContributionEmployerRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SocialContributionLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CountryPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "MM",
                            CountryName = "Myanmar",
                            CreatedAt = new DateTime(2026, 8, 11, 4, 35, 47, 129, DateTimeKind.Utc).AddTicks(2683),
                            Currency = "MMK",
                            FlagEmoji = "🇲🇲",
                            HasAgeBased = false,
                            HasProgressiveTax = true,
                            IsActive = true,
                            SocialContributionEmployeeRate = 2m,
                            SocialContributionEmployerRate = 3m,
                            SocialContributionLabel = "SSB"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "SG",
                            CountryName = "Singapore",
                            CreatedAt = new DateTime(2026, 8, 11, 4, 35, 47, 129, DateTimeKind.Utc).AddTicks(2722),
                            Currency = "SGD",
                            FlagEmoji = "🇸🇬",
                            HasAgeBased = true,
                            HasProgressiveTax = false,
                            IsActive = true,
                            SocialContributionEmployeeRate = 0m,
                            SocialContributionEmployerRate = 0m,
                            SocialContributionLabel = "CPF"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "TH",
                            CountryName = "Thailand",
                            CreatedAt = new DateTime(2026, 8, 11, 4, 35, 47, 129, DateTimeKind.Utc).AddTicks(2723),
                            Currency = "THB",
                            FlagEmoji = "🇹🇭",
                            HasAgeBased = false,
                            HasProgressiveTax = true,
                            IsActive = true,
                            SocialContributionEmployeeRate = 5m,
                            SocialContributionEmployerRate = 5m,
                            SocialContributionLabel = "SSF"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "MY",
                            CountryName = "Malaysia",
                            CreatedAt = new DateTime(2026, 8, 11, 4, 35, 47, 129, DateTimeKind.Utc).AddTicks(2725),
                            Currency = "MYR",
                            FlagEmoji = "🇲🇾",
                            HasAgeBased = false,
                            HasProgressiveTax = true,
                            IsActive = true,
                            SocialContributionEmployeeRate = 11m,
                            SocialContributionEmployerRate = 13m,
                            SocialContributionLabel = "EPF"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "PH",
                            CountryName = "Philippines",
                            CreatedAt = new DateTime(2026, 8, 11, 4, 35, 47, 129, DateTimeKind.Utc).AddTicks(2726),
                            Currency = "PHP",
                            FlagEmoji = "🇵🇭",
                            HasAgeBased = false,
                            HasProgressiveTax = true,
                            IsActive = true,
                            SocialContributionEmployeeRate = 4.5m,
                            SocialContributionEmployerRate = 9.5m,
                            SocialContributionLabel = "SSS"
                        });
                });

            modelBuilder.Entity("PayrollService.Models.EmployeeLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeLoans");
                });

            modelBuilder.Entity("PayrollService.Models.Payslip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Allowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cpfemployee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cpfemployer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtherDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SocialSecurity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThirteenthMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnpaidLeaveDays")
                        .HasColumnType("int");

                    b.Property<decimal>("UnpaidLeaveDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<decimal>("YearEndBonus")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payslips");
                });

            modelBuilder.Entity("PayrollService.Models.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxBrackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "MM",
                            Description = "0% - Up to 4.8M MMK",
                            MaxIncome = 4800000m,
                            MinIncome = 0m,
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = 2,
                            Country = "MM",
                            Description = "5% - 4.8M to 10M MMK",
                            MaxIncome = 10000000m,
                            MinIncome = 4800001m,
                            TaxRate = 5m
                        },
                        new
                        {
                            Id = 3,
                            Country = "MM",
                            Description = "10% - 10M to 20M MMK",
                            MaxIncome = 20000000m,
                            MinIncome = 10000001m,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 4,
                            Country = "MM",
                            Description = "15% - 20M to 30M MMK",
                            MaxIncome = 30000000m,
                            MinIncome = 20000001m,
                            TaxRate = 15m
                        },
                        new
                        {
                            Id = 5,
                            Country = "MM",
                            Description = "20% - Above 30M MMK",
                            MaxIncome = 999999999m,
                            MinIncome = 30000001m,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 6,
                            Country = "TH",
                            Description = "0% - Up to 150,000 THB",
                            MaxIncome = 150000m,
                            MinIncome = 0m,
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = 7,
                            Country = "TH",
                            Description = "5% - 150K to 300K THB",
                            MaxIncome = 300000m,
                            MinIncome = 150001m,
                            TaxRate = 5m
                        },
                        new
                        {
                            Id = 8,
                            Country = "TH",
                            Description = "10% - 300K to 500K THB",
                            MaxIncome = 500000m,
                            MinIncome = 300001m,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 9,
                            Country = "TH",
                            Description = "15% - 500K to 750K THB",
                            MaxIncome = 750000m,
                            MinIncome = 500001m,
                            TaxRate = 15m
                        },
                        new
                        {
                            Id = 10,
                            Country = "TH",
                            Description = "20% - 750K to 1M THB",
                            MaxIncome = 1000000m,
                            MinIncome = 750001m,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 11,
                            Country = "TH",
                            Description = "25% - 1M to 2M THB",
                            MaxIncome = 2000000m,
                            MinIncome = 1000001m,
                            TaxRate = 25m
                        },
                        new
                        {
                            Id = 12,
                            Country = "TH",
                            Description = "35% - Above 2M THB",
                            MaxIncome = 999999999m,
                            MinIncome = 2000001m,
                            TaxRate = 35m
                        },
                        new
                        {
                            Id = 13,
                            Country = "MY",
                            Description = "0% - Up to 5,000 MYR",
                            MaxIncome = 5000m,
                            MinIncome = 0m,
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = 14,
                            Country = "MY",
                            Description = "1% - 5K to 20K MYR",
                            MaxIncome = 20000m,
                            MinIncome = 5001m,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 15,
                            Country = "MY",
                            Description = "3% - 20K to 35K MYR",
                            MaxIncome = 35000m,
                            MinIncome = 20001m,
                            TaxRate = 3m
                        },
                        new
                        {
                            Id = 16,
                            Country = "MY",
                            Description = "8% - 35K to 50K MYR",
                            MaxIncome = 50000m,
                            MinIncome = 35001m,
                            TaxRate = 8m
                        },
                        new
                        {
                            Id = 17,
                            Country = "MY",
                            Description = "13% - Above 50K MYR",
                            MaxIncome = 999999999m,
                            MinIncome = 50001m,
                            TaxRate = 13m
                        },
                        new
                        {
                            Id = 18,
                            Country = "PH",
                            Description = "0% - Up to 250,000 PHP",
                            MaxIncome = 250000m,
                            MinIncome = 0m,
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = 19,
                            Country = "PH",
                            Description = "20% - 250K to 400K PHP",
                            MaxIncome = 400000m,
                            MinIncome = 250001m,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 20,
                            Country = "PH",
                            Description = "25% - 400K to 800K PHP",
                            MaxIncome = 800000m,
                            MinIncome = 400001m,
                            TaxRate = 25m
                        },
                        new
                        {
                            Id = 21,
                            Country = "PH",
                            Description = "30% - 800K to 2M PHP",
                            MaxIncome = 2000000m,
                            MinIncome = 800001m,
                            TaxRate = 30m
                        },
                        new
                        {
                            Id = 22,
                            Country = "PH",
                            Description = "32% - 2M to 8M PHP",
                            MaxIncome = 8000000m,
                            MinIncome = 2000001m,
                            TaxRate = 32m
                        },
                        new
                        {
                            Id = 23,
                            Country = "PH",
                            Description = "35% - Above 8M PHP",
                            MaxIncome = 999999999m,
                            MinIncome = 8000001m,
                            TaxRate = 35m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
